name: wowin_crm
description: Wowin CRM Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State & DI
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^9.2.1 # Optional DI to replace riverpod's provider behavior
  
  # Navigation
  go_router: ^17.1.0
  
  # HTTP
  dio: ^5.4.0
  
  # Auth & Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.0
  
  # Database lokal
  sqflite: ^2.3.0
  
  # Kamera & foto
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  
  # GPS & Free Maps (OSM)
  geolocator: ^14.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  workmanager: ^0.9.0+3
  
  # Utils
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  path: ^1.9.1
  flutter_animate: ^4.5.0
  lucide_icons: ^0.257.0
  path_provider: ^2.1.2
  camera: ^0.12.0+1
  uuid: ^4.5.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^3.2.5
  json_serializable: ^6.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
